### ISSUE TITLE
Get no output.

### ISSUE THREAD

**Issue by Steviey** [llSourcell/predicting_stock_prices#6]
I got no output, no error message running demo.py on Win7/Anaconda even while trying alternative backends. Any suggestions? I'm so disappointed now...deeply depressed.﻿

**Comment by pick1** [comment]
Same... running  jupyter and endless hang at - predict_price(dates, prices, 29)

**Comment by enderg** [comment]
I also have an endless hang at predict_price

**Comment by bsirmacek** [comment]
Same :-( endless waiting and no result.

**Comment by bsirmacek** [comment]
Okay I resolved the issue. It is working for me now. 

It looks like libraries changed their syntaxes a lot since then. 

Here how I import things: 

> import csv
> import numpy as np
> from sklearn.svm import SVR
> import matplotlib.pyplot as plt
> plt.switch_backend('TkAgg')  

Another change:
>#dates = np.reshape(dates,(len(dates), 1)) # converting to matrix of n X 1
>dates = np.reshape(dates,(-1, 1))

Also removed the color and label from plot (probably needs to be defined differently, the old way of color and label definition is not working.)
>plt.plot(dates,svr_poly.predict(dates))

**Comment by Ypsingh18** [comment]
Hey so were u actually able to predict future values ? because each time i return     return svr_rbf.predict(x)[0] i keep getting the error to re shape my array to a (1,-1)

**Comment by Ypsingh18** [comment]
ValueError: Expected 2D array, got scalar array instead:
array=14.0.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
